config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  devise_for :users
  resources :flats do
    resources :bookings, only: %i[new create]
  end
  resources :bookings, only: %i[index show edit update destroy] do
    resources :reviews, only: %i[new create]
  end

  get "/my_listings", to: "pages#my_listings"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flat
  belongs_to :user
  has_one :review, dependent: :destroy

  validates :start_date, presence: true
  validates :end_date, presence: true
end

app/models/flat.rb
class Flat < ApplicationRecord
  has_one_attached :photo
  belongs_to :user
  has_many :bookings
  has_many :reviews, through: :bookings

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  validates :address, presence: true
  validates :city, presence: true
  validates :flat_location, presence: true
  validates :price, presence: true

  COUNTRIES = ['NL', 'FR', 'GE']
  CITIES = ['Amsterdam', 'Paris', 'Berlin']

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
  validates :rating, presence: true
  validates :title, presence: true
  validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings
  has_many :flats
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  include Pundit::Authorization

  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name phone_number profile_pic role])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name phone_number profile_pic role email])
  end

  private

  def skip_pundit?
    # params[:controller] == "pages" && params[:action] == "home"
    # params[:controller] == "flats" && params[:action] == "index"
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)|(^flats$)|(^bookings$)/
    # params[:controller] == "pages" && params[:action] == "home" ||
    # params[:controller] == "flats" && params[:action] == "index"
  end

  def user_not_authorized
    redirect_back(fallback_location: root_path, alert: "You are not authorized to perform this action.")
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: %i[show edit destroy update]

  def index
    @bookings = current_user.bookings
  end

  # show: will display the details of a specific booking, such as the price and location
  def show
    authorize @booking
    @flat = @booking.flat
    # @booking = Booking.find(params[:id])
    # @flat = Flat.find(@booking.flat.id)
    @review = Review.new
  end

  # new: will display a form to create a new booking
  def new
    @booking = Booking.new
    @flat = Flat.find(params[:flat_id])
    authorize @booking
  end

  def create
    @booking = Booking.new(booking_params)
    @flat = Flat.find(params[:flat_id])
    @booking.flat = @flat
    @booking.user = current_user
    authorize @booking

    if @booking.save
      redirect_to booking_path(@booking), notice: "Booking confirmed"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize @booking
  end

  def update
    authorize @booking
    if @booking.update(booking_params)
      redirect_to bookings_path(@booking), notice: "Booking edited added"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @booking
    @booking.destroy
    # No need for app/views/restaurants/destroy.html.erb
    redirect_back(fallback_location: root_path)#, status: :see_other
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]
  before_action :set_flat, only: %i[show edit update destroy]

  # index: will display a list of all the available flats
  def index
    @query = params[:search].nil? ? "" : params[:search]
    if @query == ""
      @flats = Flat.all
    else
      @flats = Flat.where("lower(city) LIKE ? OR lower(flat_location) LIKE ?", @query.downcase + "%", @query.downcase + "%")
    end

    @markers = @flats.geocoded.map do |flat|
      {
        lat: flat.latitude,
        lng: flat.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {flat: flat})
      }
    end
    @flat = Flat.new
  end

  # show: will display the details of a specific flat, such as the price and location
  def show
    authorize(@flat)
    @booking = @flat.bookings.find_by(user_id: current_user.id) if nil?
    @markers = Flat.where(id: [@flat.id]).geocoded.map do |flat|
      {
        lat: flat.latitude,
        lng: flat.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: {flat: flat})
      }
    end
  end

  # new: will display a form to create a new flat
  def new
    @flat = Flat.new
    authorize(@flat)
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.user = current_user
    authorize(@flat)
    if @flat.save
      redirect_to flat_path(@flat), notice: "Flat added"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize(@flat)
  end

  def update
    authorize(@flat)
    if @flat.update(flat_params)
      redirect_to flat_path(@flat), notice: "Flat updated"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize(@flat)
    @flat.destroy
    # No need for app/views/restaurants/destroy.html.erb
    redirect_to my_listings_path, status: :see_other
  end

  private

  def flat_params
    params.require(:flat).permit(:price, :address, :city, :flat_location, :photo, :description)
  end

  def set_flat
    @flat = Flat.find(params[:id])
  end

  # create: will receive the form data submitted through the new action and create a new flat in the database
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end

  def my_listings
    @flats = current_user.flats
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @reviews = Review.all
  end

  def new
    @review = Review.new
    authorize(@review)
    @booking = Booking.find(params[:booking_id])
  end

  def create
    @review = Review.new(review_params)
    @booking = Booking.find(params[:booking_id])
    @flat = Flat.find(@booking.flat.id)
    @review.booking = @booking
    authorize(@review)
    if @review.save
      redirect_to flat_path(@booking.flat), notice: "Review created successfully!"
    else
      render 'bookings/show', status: :unprocessable_entity, flat: @flat, alert: "Failed to create review"
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :title, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/_new.html.erb
<%= simple_form_for [flat, booking], :html=> { class: 'form-group booking-form' } do |f| %>
  <h1 class="text-black">Your booking for <%=@flat.address%>, <%=@flat.flat_location%> </h1>
  <%= f.input :start_date, input_html: { class: 'form-control form-control-sm' } %>
  <%= f.input :end_date, input_html: { class: 'form-control form-control-sm' } %>
  <%= f.submit class:"btn btn-primary btn-sm rounded-5" %>
<% end %>

<%= button_to 'Book now', listing_bookings_path(@listing), method: :post, onclick: 'displayLogo()' %>

app/views/bookings/edit.html.erb
<div class="container">
    <div class="row justify-content-center align-items-center m-5 p-4">
      <div class="booking-form col-8 text-center">
        <%= simple_form_for @booking, :html=> { class: 'form-group' } do |f| %>
          <h1 class="text-black">Edit</h1>
          <%= f.input :start_date, label: "Check-in date", input_html: { class: 'form-control mb-4' } %>
          <%= f.input :end_date, label: "Check-out date", input_html: { class: 'form-control mb-4' } %>
          <%# <%= image_tag f.object.img.url if f.object.image.present? %>
          <%= f.submit "Update" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/bookings/index.html.erb
<% if @bookings == [] %>
  <div class="mt-5 p-4 text-black">
    <h1 class="text-black text-center">No bookings yet...</h1>
    <br>
    <div class="text-center mb-5">
      <h1><%= link_to flats_path, class: "btn btn-primary btn-flat rounded-5" do %>
        <i class="fa-solid fa-plus"></i>  Book a flat!
      <% end %></h1>
    </div>
  </div>
<% else %>

  <div class="mt-5 p-4 text-black">
    <h1 class="text-black text-center">My bookings</h1>
  </div>

  <div class="d-flex justify-content-center m-4">
    <div class="flats-container">
      <% @bookings.each do |booking| %>
        <div class="col">
          <div class="card h-100">
            <% if booking.flat.photo.key %>
              <img src="<%= cl_image_path(booking.flat.photo.key)%>" class="card-img-top" alt="<%= booking.flat.city %>">
            <% else %>
              <img src="https://via.placeholder.com/300x200.png?text=No+Image" class="card-img-top" alt="<%= booking.flat.city %>">
            <% end %>
            <div class="card-body">
              <h4>From <strong><%= booking.start_date %></strong> </h4>
              <h4>To <strong><%= booking.end_date %></strong></h4>
              <h5 class="card-title"><%= booking.flat.address %></h5>
              <h5 class="card-title"><%= booking.flat.city %></h5>
              <p class="card-text">Hosted by: <%= booking.flat.user.first_name %></p>
              <p class="card-text"><%= number_to_currency(booking.flat.price, unit: "€", precision: 0) %> / night</p>
              <a href="<%= flat_path(booking.flat) %>" class="btn btn-secondary">Flat details</a>
              <a href="<%= edit_booking_path(booking) %>" class="btn btn-secondary"><i class="fa-solid fa-pen-to-square"></i></a>
              <a href="<%= booking_path(booking) %>" class="btn btn-secondary my-2 text-white" data-turbo-method="delete" data-turbo-confirm="Are you sure?"><i class="fa-solid fa-square-xmark"></i></a>
              <%= link_to "Add review", new_booking_review_path(booking), class: "btn btn-primary text-white" %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/bookings/show.html.erb
<br>
<div id="animation" class="m-5 p-4 text-center bg-dark rounded-4">
  <h1>Booking successful!</h1>

  <%= image_tag(
    "le-wagon-logo-svg.svg",
    style: "display: none; width: 230px;",
    id: "my-image"
  ) %>
  <img src="" alt="" style="display: none;" id="myimage">

  <h3 class="text-white">Your stay in
    <%= @flat.address %>,
    <%= @flat.city %>,
    <%= @flat.flat_location %></h3>
  <h3 class="text-white">From
    <strong><%= @booking.start_date %></strong>
    to
    <strong><%= @booking.end_date %></strong></h3>

  <p style="color: white;">Price per night: €<%= @flat.price %></p>
</div>

<div class="text-center mb-5 pb-5">
  <h1><%= link_to bookings_path, class: "btn btn-primary btn-flat rounded-5 text-white" do %>
    <i class="fa-solid fa-calendar-days"></i>  View my bookings
  <% end %></h1>
</div>
<br><br>

app/views/flats/_info_window.html.erb
<h5><%= flat.address %>, <%= flat.city %>, <%= flat.flat_location %></h5>
<h6>Price per night: <strong>€<%= flat.price %></strong></h6>

<%= link_to "See flat in detail", flat_path(flat) %>

app/views/flats/edit.html.erb
<div class="container">
  <div class="row justify-content-center align-items-center m-5 p-4 border border-3 rounded-5">
    <%= simple_form_for @flat, :html=> { class: 'form-group p-5' } do |f| %>
      <h1 class="text-black">Edit</h1>
      <%= f.input :price %>
      <%= f.input :address, hint: "Streetname and postcode" %>
      <%= f.input :description %>
      <%= f.input :city, collection: Flat::CITIES, as: :radio_buttons %>
      <%= f.input :flat_location, collection: Flat::COUNTRIES, as: :radio_buttons %>
      <%# <%= image_tag f.object.img.url if f.object.image.present? %>
      <%= f.submit %>
    <% end %>
  </div>
</div>

app/views/flats/index.html.erb
<% if @flats.empty? %>
  <div class="m-5 pt-4 px-5 text-black">

    <h1 class="text-black">No flats in "<%= @query.upcase %>"</h1>
    <h1 class="text-black">
      <%= link_to root_path, class: "btn btn-primary btn-flat rounded-5" do %>
        <i class="fas fa-search text-white"></i> Search again
      <% end %>
    </h1>
  </div>
<% elsif @query.present? %>
  <div class="m-5 pt-4 px-5 text-black">

    <h1 class="text-black">Flats in "<%= @query.upcase %>"</h1>
  </div>
<% end %>

<form novalidate="novalidate" class="simple_form search" action="/flats" accept-charset="UTF-8" method="get">
  <div class="d-flex justify-content-center w-50 m-5 text-center ps-5">
    <input class="form-control rounded-pill me-3" type="text" name="search" id="search_query" placeholder="Search by location">
    <button name="button" type="submit" class="btn btn-primary rounded-pill ps-4 pe-3 text-white text-center">
      <i class="fas fa-search me-2"></i>
    </button>
  </div>
</form>

<div class="d-flex justify-content-center m-5">
  <div class="me-5 rounded-4" style="width: 400px; height: 60vh; position: sticky; top: 36px"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>

  <div class="">
    <%= render "shared/flatspage", flats: @flats  %>
  </div>
</div>

app/views/flats/new.html.erb
<div class="container">
  <div class="row justify-content-center align-items-center m-5 p-4 border border-3 rounded-5">
    <%= simple_form_for @flat, :html=> { class: 'form-group p-5' } do |f| %>
      <h1 class="text-black">Create new flat</h1>
      <%= f.input :price, collection: 1..100, input_html: { class: 'form-control' } %>
      <%= f.input :address, hint: "Streetname and postcode" %>
      <%= f.input :description %>
      <%= f.input :city, collection: Flat::CITIES, as: :radio_buttons %>
      <%= f.input :flat_location, collection: Flat::COUNTRIES, as: :radio_buttons %>
      <%= f.input :photo, as: :file %>
      <%= f.submit class:"btn btn-primary rounded-5" %>
    <% end %>
  </div>
</div>

app/views/flats/show.html.erb
<div class="page-container">
  <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.6)), url('<%= cl_image_path(@flat.photo.key) %>'); max-width:100%; max-height:100%; background-size: cover;">
    <div class="banner-container">
    <div class="">
      <%= link_to :back , class: "text-white" do%>
        <i class="fa-solid fa-arrow-left"></i> Back
      <% end %>
    </div>
      <div>
        <h1>Flat in
          <%= @flat.city %>, <%= @flat.flat_location %></h1>
        <p><%= @flat.address %></p>
      </div>
    </div>
  </div>

  <div class="info-container px-5 py-3 mb-3 mx-5">
    <%# style="display: flex; flex-wrap: wrap;"> %>
    <div class="row justify-content-center px-3">
      <div class=" col-7">

        <div class="apartment-info">
          <br>
          <h2 class="gray">
            <i class="fa-solid fa-house text-d"></i>  50m<sup>2</sup> &nbsp | &nbsp
            <i class="fa-solid fa-user"></i>  3-4 &nbsp | &nbsp
            <i class="fa-solid fa-bed"></i>  2 &nbsp | &nbsp
            <i class="fa-solid fa-restroom"></i>  1.5 &nbsp | &nbsp
            <i class="fa-sharp fa-solid fa-door-closed"></i>  Self check-in
          </h2>
          <br>
          <br>
          <h3>€<%= @flat.price %> / night</h3>
          <p><%= @flat.description %></p>
          <br>
          <br>
          <br>
          <h4>Rental unit hosted by <%= @flat.user.first_name %></h4>
        </div>

        <div
          class="my-5 border p-5"
          style="width: 780px; height: 60vh;"
          data-controller="map"
          data-map-markers-value="<%= @markers.to_json %>"
          data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
        >
        </div>

        <% if @flat.reviews.present? %>
          <h4>Reviews</h4>
        <% end %>

        <div class="reviews">
          <% @flat.reviews.each do |review| %>
            <div class="review">
              <p>
                Rating:
                <%= review.rating %>
                &#9733;</p>
              <p>Title:
                <%= review.title %></p>
              <p>Description:
                <%= review.description %></p>
            </div>
          <% end %>
        </div>

      </div>

      <div class="col-4 ms-5">
        <div class="booking-form">
          <%= render "shared/newbooking", flat: @flat, booking: Booking.new %>
        </div>
      </div>

    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirbnbTabinav</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
  </head>

  <body>
    <%= render "shared/flashes" %>
    <%= render "shared/navbar" unless ["devise/sessions", "devise/registrations"].include? params[:controller] %>
    <%= yield %>
    <%= render "shared/footer" unless ["devise/sessions", "devise/registrations"].include? params[:controller] %>
  </body>
</html>

app/views/pages/home.html.erb
<div style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('https://res.cloudinary.com/dfhlfj6vs/image/upload/v1677856097/background-1_hg8knr.jpg'); max-width:100%; max-height:100%; background-size: cover;">
  <div class="home-container text-center d-flex justify-content-center align-items-center vh-100">
    <div class="p-5 bg-white rounded-5 shadow">
      <h3 class="mb-4 text-black">Find unique places to stay and things to do</h3>
      <form novalidate="novalidate" class="simple_form search" action="/flats" accept-charset="UTF-8" method="get">
        <div class="search-form-control form-group">
          <label for="search_query" class="visually-hidden">Where are you going?</label>
          <input class="form-control form-control-lg rounded-pill" type="text" name="search" id="search_query" placeholder="Where are you going?">
        </div>
        <div class="d-flex justify-content-center mt-4">
          <button name="button" type="submit" class="btn btn-primary btn-lg rounded-pill px-5 text-white">
            <i class="fas fa-search me-2 text-white"></i> Search
          </button>
        </div>
      </form>
    </div>
  </div>
</div>

app/views/pages/my_listings.html.erb
<% if @flats == [] %>
  <div class="mt-5 p-4 text-black">
    <h1 class="text-black text-center">No listing yet...</h1>
    <br>
    <div class="text-center mb-5">
      <h1><%= link_to new_flat_path, class: "btn btn-primary btn-flat rounded-5" do %>
        <i class="fa-solid fa-plus"></i>  List a flat!
      <% end %></h1>
    </div>
  </div>
<% else %>
  <div class="mt-5 mx-5 px-4 text-black row justify-content-center">
    <h1 class="col-3 text-black">My Listings</h1>
    <br>
      <div class="col-5 text-end">
        <h1><%= link_to new_flat_path, class: "btn btn-primary btn-flat rounded-5 text-white" do %>
        <i class="fa-solid fa-plus"></i>  List a new flat!
      <% end %></h1>
    </div>
  </div>

  <div class="m-4">
     <% @flats.each do |flat| %>
      <div class="row m-5 justify-content-center">
        <div class="card col-3 h-100 m-3">
          <% if flat.photo.key %>
            <img src="<%= cl_image_path(flat.photo.key)%>" class="card-img-top" alt="<%= flat.city %>">
          <% else %>
            <img src="https://via.placeholder.com/300x200.png?text=No+Image" class="card-img-top" alt="<%= flat.city %>">
          <% end %>
          <div class="card-body">
            <h5 class="card-title"><%= flat.address %>, <%= flat.city %>, <%= flat.flat_location %></h5>
            <p class="card-text">Flat Owner: <%= flat.user.first_name %></p>
            <p class="card-text"><%= number_to_currency(flat.price, unit: "€", precision: 0) %> / night</p>
            <a href="<%= flat_path(flat) %>" class="btn btn-flat">View details</a>
            <a href="<%= edit_flat_path(flat) %>" class="btn btn-secondary">Edit flat</a>

            <% if flat.bookings == [] %>
              <a href="<%= flat_path(flat) %>" class="btn btn-primary my-2 text-white" data-turbo-method="delete" data-turbo-confirm="Are you sure?">Remove flat</a>
            <% end %>
          </div>
        </div>

        <div class="col-5 booking-tag">
          <% if flat.bookings == [] %>
            <div class="p-3 text-dark m-3">
              <h2>No bookings for this flat at the moment.</h2>
            </div>
          <% else %>
            <% flat.bookings.each do |booking| %>
              <div class="border border-1 p-3 bg-light text-dark rounded-3 m-3">
                <h2><%= booking.user.first_name %> : From <strong><%= booking.start_date %></strong> to <strong><%= booking.end_date %></strong></h2>
                <%= link_to "Reject Booking", booking_path(booking), data: {turbo_method: :delete, turbo_confirm: "Are you sure?", class: "btn btn-secondary"} %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/reviews/_new.html.erb
<%= simple_form_for [@booking, Review.new] do |f| %>
  <%= f.input :rating, label: "Rating" %>
  <%= f.input :title, label: "Title" %>
  <%= f.input :description, label: "Description" %>
  <%= f.button :submit, "Submit Review" %>
<% end %>

app/views/reviews/new.html.erb
<div style="min-height: 75vh">
  <div class="container w-25 bg-white mt-5 p-5">
    <h4>How did you like your booking?</h4>
    <%= simple_form_for [@booking, Review.new] do |f| %>
      <%= f.input :rating, label: "Rating" %>
      <%= f.input :title, label: "Title" %>
      <%= f.input :description, label: "Description" %>
      <%= f.submit class:"btn btn-primary btn-sm rounded-5" %>
    <% end %>
  </div>
</div>

app/views/shared/_createflat.html.erb
<%= simple_form_for @flat, :html=> { class: 'form-group p-5' } do |f| %>
  <h1 class="text-black">Create new flat</h1>
  <%= f.input :price, collection: 1..100, input_html: { class: 'form-control' } %>
  <%= f.input :address, hint: "Streetname and postcode" %>
  <%= f.input :city, collection: Flat::CITIES, as: :radio_buttons %>
  <%= f.input :flat_location, collection: Flat::COUNTRIES, as: :radio_buttons %>
  <%= f.input :photo, as: :file %>
  <%= f.submit class:"btn btn-primary rounded-5" %>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_flatspage.html.erb
<div class="flats-container">
  <% @flats.each do |flat| %>
      <div class="card h-100 rounded-4 overflow-hidden">
        <% if flat.photo.key %>
          <img src="<%= cl_image_path(flat.photo.key)%>" class="card-img-top" alt="<%= flat.city %>">
        <% else %>
          <img src="https://via.placeholder.com/300x200.png?text=No+Image" class="card-img-top" alt="<%= flat.city %>">
        <% end %>
        <div class="card-body">
          <h3 class="card-title text-black font-weight-bold"><%= flat.city %></h3>
          <p class="card-text"> <%= flat.address %></p>
          <br>
          <div class="d-flex justify-content-between align-items-center">
            <div>
              <a href="<%= flat_path(flat) %>" class="btn btn-secondary rounded-pill">View details</a>
            </div>
            <div>
              <p class="card-text text-black"><%= number_to_currency(flat.price, unit: "€", precision: 0) %> / night</p>
            </div>
          </div>
        </div>
      </div>
  <% end %>
</div>


  <%# <% if flat.photo.key  %>
      <%# <%= cl_image_tag flat.photo.key, height: 300, width: 400, crop: :fill %>
    <%# <% end %>

app/views/shared/_footer.html.erb
<footer class="bg-light p-5">
  <div class="mx-5 px-5" style="height: 100px">
    <div class="row">
      <div class="col-6 mb-2">
        <div class="mb-2">
          <ul class="list-unstyled list-inline mb-4">
            <li class="list-inline-item"><a href="#">Home</a></li>
            <li class="list-inline-item"><a href="#">Flights</a></li>
            <li class="list-inline-item"><a href="#">Hotels</a></li>
            <li class="list-inline-item"><a href="#">Destinations</a></li>
            <li class="list-inline-item"><a href="#">Blog</a></li>
          </ul>
        </div>
        <div class="">
          <p class="">This footer is made with <i class="fas fa-heart"></i> at Le Wagon</p>
        </div>

      </div>

      <div class="col-6 text-end">
        <p>We are a team of passionate travelers who love to explore the world and help others make their travel dreams come true.</p>
        <div class="footer-icons mb-2">
          <a href="#"><i class="fab fa-github me-3"></i></a>
          <a href="#"><i class="fab fa-linkedin"></i></a>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_new.html.erb
<%= simple_form_for [flat, booking], html: {class: "form-group"} do |f| %>
  <h1 class="text-black mb-4">Book this apartment</h1>
  <%= f.input :start_date, label: "Check-in date", input_html: { class: 'form-control mb-4' } %>
  <%= f.input :end_date, label: "Check-out date", input_html: { class: 'form-control mb-4' } %>
  <%= f.submit "Book now", class: "btn btn-primary rounded-5" %>
<% end %>

app/views/shared/_newbooking.html.erb
<%= simple_form_for [flat, booking], html: {class: "form-group"} do |f| %>
  <h1 class="text-black mb-4">Book this apartment</h1>
  <%= f.input :start_date, label: "Check-in date", input_html: { class: 'form-control mb-4' } %>
  <%= f.input :end_date, label: "Check-out date", input_html: { class: 'form-control mb-4' } %>
  <%= f.submit "Book now", class: "btn btn-primary rounded-5" %>
<% end %>